In [1]:
from sklearn.datasets import load_iris
import numpy as np

Xiris, yiris = load_iris(return_X_y=True)


In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

n_neighbors=[2,3,4,5,10]

print('UNSTRATIFIED TESTSETS')
print()

for n in n_neighbors:
    knn = KNeighborsClassifier(n_neighbors=n)
    X_train, X_test, y_train, y_test = train_test_split(
       Xiris, 
       yiris, 
       test_size = 0.25,
       random_state=10)

    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)

    print('number of neighbours: ', n)
    print('accuracy: ', accuracy_score(y_test, y_pred))
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion matrix: ')
    print(cm)
    print()

print('STRATIFIED TESTSETS')
print()

for n in n_neighbors:
    knn = KNeighborsClassifier(n_neighbors=n)
    X_train, X_test, y_train, y_test = train_test_split(
       Xiris, 
       yiris, 
       test_size = 0.25,
       random_state=10, stratify=yiris)

    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)

    print('number of neighbours: ', n)
    print('accuracy: ', accuracy_score(y_test, y_pred))
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion matrix: ')
    print(cm)
    print()



UNSTRATIFIED TESTSETS

number of neighbours:  2
accuracy:  0.9473684210526315
Confusion matrix: 
[[11  0  0]
 [ 0 14  1]
 [ 0  1 11]]

number of neighbours:  3
accuracy:  0.9736842105263158
Confusion matrix: 
[[11  0  0]
 [ 0 14  1]
 [ 0  0 12]]

number of neighbours:  4
accuracy:  0.9736842105263158
Confusion matrix: 
[[11  0  0]
 [ 0 14  1]
 [ 0  0 12]]

number of neighbours:  5
accuracy:  0.9736842105263158
Confusion matrix: 
[[11  0  0]
 [ 0 14  1]
 [ 0  0 12]]

number of neighbours:  10
accuracy:  0.9736842105263158
Confusion matrix: 
[[11  0  0]
 [ 0 15  0]
 [ 0  1 11]]

STRATIFIED TESTSETS

number of neighbours:  2
accuracy:  1.0
Confusion matrix: 
[[12  0  0]
 [ 0 13  0]
 [ 0  0 13]]

number of neighbours:  3
accuracy:  1.0
Confusion matrix: 
[[12  0  0]
 [ 0 13  0]
 [ 0  0 13]]

number of neighbours:  4
accuracy:  0.9736842105263158
Confusion matrix: 
[[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]

number of neighbours:  5
accuracy:  1.0
Confusion matrix: 
[[12  0  0]
 [ 0 13  0]
 [ 0  